version: "3.4"

# #############################################################
# Docker Swarm Visualization - Containers per Node
# #############################################################

services:
  viz:
    image: dockersamples/visualizer
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - "8004:8080"
    deploy:
      mode: replicated
      replicas: 1
#      placement:
#        constraints: [node.role != manager]
      labels:
        - "traefik.enable=false"
